[project]
name = "energent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=6.0.0",
    "gtts>=2.5.4",
    "protobuf>=7.35.1",
    "pyaudio>=0.2.14",
    "pygame>=2.6.1",
    "python-dotenv>=1.2.2",
    "requests>=2.31.0",
    "sentencepiece>=0.1.99",
    "speechrecognition>=3.17.0",
    "tiktoken>=0.13.0",
    "torch>=2.1.0",
    "transformers>=4.40.0",
]
